INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Ocean Cleanup", "Environment", 400, "6/1/17", "6/30/17");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Cat & Dog Food Drive", "Animals", 500, "6/1/17", "6/30/17");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Toys for Children", "Children", 125, "6/1/17", "6/30/17");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Meals on Wheels", "Homeless", 75, "6/1/17", "6/30/17");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Alzheimers Run", "Seniors", 100, "6/1/17", "6/30/17");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Counseling Sessions", "Domestic Violence", 65, "7/1/17", "7/31/17");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Wig Making", "Cancer Survivors", 1000, "7/1/17", "7/31/17");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Dog Harnesses", "Blind & Deaf", 500, "7/1/17", "7/31/17");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Musical Instruments", "Developmental Disabilities", 315, "7/1/17", "7/31/17");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("PTSD Counseling", "Military", 80, "7/1/17", "7/31/17");

INSERT INTO users (name, age) VALUES ("Alexis Dorn", 26);
INSERT INTO users (name, age) VALUES ("Jacob Dorn", 27);
INSERT INTO users (name, age) VALUES ("Claire Dorn", 24);
INSERT INTO users (name, age) VALUES ("Patrick Dorn", 51);
INSERT INTO users (name, age) VALUES ("Abby Dorn", 50);
INSERT INTO users (name, age) VALUES ("Bill Dorn", 85);
INSERT INTO users (name, age) VALUES ("Steve Ulrich", 49);
INSERT INTO users (name, age) VALUES ("Amy Ulrich", 45);
INSERT INTO users (name, age) VALUES ("Chris Johnson", 38);
INSERT INTO users (name, age) VALUES ("Jim Ulrich", 84);
INSERT INTO users (name, age) VALUES ("Alisha Bowman", 27);
INSERT INTO users (name, age) VALUES ("Kayla Payne", 27);
INSERT INTO users (name, age) VALUES ("Jason Banning", 27);
INSERT INTO users (name, age) VALUES ("Morgan Johnson", 26);
INSERT INTO users (name, age) VALUES ("Casey Ulrich", 27);
INSERT INTO users (name, age) VALUES ("Taylor Ulrich", 24);
INSERT INTO users (name, age) VALUES ("Kyle Ulrich", 31);
INSERT INTO users (name, age) VALUES ("Sean Pinnow", 32);
INSERT INTO users (name, age) VALUES ("Brady Ulrich", 19);
INSERT INTO users (name, age) VALUES ("Jaren Ulrich", 22);

INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 1, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 1, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 2, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 2, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 3, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 3, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 4, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 5, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 5, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 6, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 6, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 6, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 6, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 7, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 7, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 8, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 8, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 9, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 10, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (30, 11, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 12, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 13, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 14, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 15, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 16, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15, 17, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 18, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15, 19, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 20, 1);





-- INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Food", "Children","10000", "5/16/18","5/10/19");
-- INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Hospital", "Environment","5500", "10/5/18", "7/15/19");
-- INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Education", "West","20000", "1/31/18", "1/30/19");
-- INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Water", "Homeless","500", "1/1/17", "6/2/17");
-- INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Medicine", "Police Officer","3000", "3/4/18", "3/2/19");
-- INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Musical Instruments", "Students","1500", "1/5/18", "7/16/18");
-- INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Flying Boat", "Automobile","5550", "3/4/18", "3/2/19");
-- INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Teleporter", "Hardware", "12000", "5/16/18", "5/10/19");
-- INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Wig Making", "Cancer Survivors","4000", "2/5/16", "2/2/17");
-- INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Laptop", "Repair","45000", "2/5/16", "2/2/17");
--
--
-- INSERT INTO users (id,name, age) VALUES (1,"Peter","22");
-- INSERT INTO users (id,name, age) VALUES (2,"Christopher", "25");
-- INSERT INTO users (id,name, age) VALUES (3,"David", "30");
-- INSERT INTO users (id,name, age) VALUES (4,"Andy", "26");
-- INSERT INTO users (id,name, age) VALUES (5,"Alexandro","27");
-- INSERT INTO users (id,name, age) VALUES (6,"Alix", "20");
-- INSERT INTO users (id,name, age) VALUES (7,"Noel", "21");
-- INSERT INTO users (id,name, age) VALUES (8,"Judith", "30");
-- INSERT INTO users (id,name, age) VALUES (9,"Medjine", "25");
-- INSERT INTO users (id,name, age) VALUES (10,"Christina", "29");
-- INSERT INTO users (id,name, age) VALUES (11,"Charles", "41");
-- INSERT INTO users (id,name, age) VALUES (12,"Den", "19");
-- INSERT INTO users (id,name, age) VALUES (13,"Cedric", "19");
-- INSERT INTO users (id,name, age) VALUES (14,"Cyara", "20");
-- INSERT INTO users (id,name, age) VALUES (15,"Joana", "49");
-- INSERT INTO users (id,name, age) VALUES (16,"Ruth", "45");
-- INSERT INTO users (id,name, age) VALUES (17,"Katiana", "19");
-- INSERT INTO users (id,name, age) VALUES (18,"Handy", "34");
-- INSERT INTO users (id,name, age) VALUES (19,"Thomas", "55");
-- INSERT INTO users (id,name, age) VALUES (20,"Dave", "35");
--
-- INSERT INTO pledges (amount, user_id, project_id) VALUES (100,1,2);
-- INSERT INTO pledges (amount, user_id, project_id) VALUES (400,3,4);
-- INSERT INTO pledges (amount, user_id, project_id) VALUES (50,3,5);
-- INSERT INTO pledges (amount, user_id, project_id) VALUES (200,2,4);
-- INSERT INTO pledges (amount, user_id, project_id) VALUES (50,5,4);
-- INSERT INTO pledges (amount, user_id, project_id) VALUES (100,2,2);
-- INSERT INTO pledges (amount, user_id, project_id) VALUES (450,6,3);
-- INSERT INTO pledges (amount, user_id, project_id) VALUES (40,9,9);
-- INSERT INTO pledges (amount, user_id, project_id) VALUES (50,6,8);
-- INSERT INTO pledges (amount, user_id, project_id) VALUES (100,10,9);
-- INSERT INTO pledges (amount, user_id, project_id) VALUES (30,7,8);
-- INSERT INTO pledges (amount, user_id, project_id) VALUES (50,5,5);
-- INSERT INTO pledges (amount, user_id, project_id) VALUES (40,4,4);
-- INSERT INTO pledges (amount, user_id, project_id) VALUES (45,2,4);
-- INSERT INTO pledges (amount, user_id, project_id) VALUES (35,5,5);
-- INSERT INTO pledges (amount, user_id, project_id) VALUES (10,11,4);
-- INSERT INTO pledges (amount, user_id, project_id) VALUES (25,12,4);
-- INSERT INTO pledges (amount, user_id, project_id) VALUES (45,7,4);
-- INSERT INTO pledges (amount, user_id, project_id) VALUES (30,8,8);
-- INSERT INTO pledges (amount, user_id, project_id) VALUES (200,13,10);
-- INSERT INTO pledges (amount, user_id, project_id) VALUES (55,13,11);
-- INSERT INTO pledges (amount, user_id, project_id) VALUES (45,14,14);
-- INSERT INTO pledges (amount, user_id, project_id) VALUES (40,12,2);
-- INSERT INTO pledges (amount, user_id, project_id) VALUES (300,3,15);
-- INSERT INTO pledges (amount, user_id, project_id) VALUES (200,12,2);
-- INSERT INTO pledges (amount, user_id, project_id) VALUES (200,16,11);
-- INSERT INTO pledges (amount, user_id, project_id) VALUES (100,17,5);
-- INSERT INTO pledges (amount, user_id, project_id) VALUES (45,11,18);
-- INSERT INTO pledges (amount, user_id, project_id) VALUES (35,18,19);
-- INSERT INTO pledges (amount, user_id, project_id) VALUES (55,19,20)
